### ISSUE TITLE
nautilus script manager uses wrong folder since Ubuntu 13.10

### ISSUE THREAD

**Issue by carlos22** [abandholm/seafile-share-link#2]
Not really an issue with the script, but if someone wonders.
The folder changed from `~/.gnome2/nautilus-scripts/` to `~/.local/share/nautilus/scripts/`

Manual enable of the script:

``` sh
ln -s /usr/share/nautilus-scripts/nautilus-seafile-share-link ~/.local/share/nautilus/scripts/
```

**Comment by abandholm** [comment]
You're absolutely right! It seems that both `nautilus-script-manager` and `nautilus-scripts-manager` are buggy, because they do not create the correct symlink. How weird.

I suppose I could change the installer to create the link in the correct place, but then users can't remove it easily. Hmm.

Thanks for the report. I thought nobody was using this ;-)
